# Generated by Django 5.2.17 on 2026-08-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_analytics", "0034_backfill_feature_request_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="custompropertysyncrun",
            name="saved_query_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
