# Generated by Django 5.2.17 on 2026-08-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replay_vision", "0077_replayscanner_deep_read_bytes_by_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="replayscanner",
            name="fast_read_bytes_by_hour",
            field=models.JSONField(
                blank=True,
                help_text="ClickHouse read bytes per hour bucket for the frequent sweep's own queries; drives its throttle, so backfill and catch-up reads do not stretch the cadence users see.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="replayscanner",
            name="sweep_throttle_factor_override",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Manual cadence-stretch multiplier for the frequent sweep; overrides its computed read-budget throttle. 1 disables throttling; null means automatic. Does not affect the deep catch-up pass, which stretches on its own spend.",
                null=True,
            ),
        ),
    ]
